version: "3.5"
services:
  server:
    container_name: wolpertinger-node
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - 8080:8080
networks:
  default:
    name: wolpertinger